modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/aleksalfi/curvegen/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="optional"
reason="Needed for Create schematic export/deploy integration and copycat materials."
versionRange="${create_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="copycats"
type="optional"
reason="Needed for smooth curve edges and ramps using Copycat Layers."
versionRange="[3.0.0,)"
ordering="AFTER"
side="BOTH"
